# Generated by Django 5.2.14 on 2026-05-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otpverification_serviceprovider_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('requirement', models.TextField(help_text='Description of how to earn this badge')),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends Only'), ('private', 'Private')], default='public', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('deactivation_requested', models.BooleanField(default=False)),
                ('deactivation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to='api.userprofile')),
            ],
            options={
                'db_table': 'account_settings',
            },
        ),
        migrations.CreateModel(
            name='TravelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_destinations', models.TextField(blank=True, help_text='Comma separated list of preferred destinations')),
                ('travel_style', models.CharField(choices=[('adventure', 'Adventure'), ('relaxed', 'Relaxed'), ('cultural', 'Cultural'), ('budget', 'Budget'), ('mix', 'Mix')], default='mix', max_length=20)),
                ('group_size_preference', models.PositiveIntegerField(blank=True, help_text='Preferred group size', null=True)),
                ('languages_spoken', models.TextField(blank=True, help_text='Comma separated list of languages')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to='api.userprofile')),
            ],
            options={
                'db_table': 'travel_preferences',
            },
        ),
        migrations.CreateModel(
            name='TravelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips_logged', models.PositiveIntegerField(default=0)),
                ('destinations_visited', models.PositiveIntegerField(default=0)),
                ('stories_posted', models.PositiveIntegerField(default=0)),
                ('reviews_written', models.PositiveIntegerField(default=0)),
                ('leaderboard_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_stats', to='api.userprofile')),
            ],
            options={
                'db_table': 'travel_stats',
            },
        ),
        migrations.CreateModel(
            name='TripStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='story_covers/')),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stories', to='api.userprofile')),
            ],
            options={
                'db_table': 'trip_stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='api.userprofile')),
            ],
            options={
                'db_table': 'user_badges',
                'unique_together': {('user_profile', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='api.userprofile')),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('user_profile', 'destination')},
            },
        ),
    ]
