# Generated by Django 5.2.14 on 2026-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_badge_accountsettings_travelpreferences_travelstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='deactivation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
