# Generated by Django 5.2.14 on 2026-05-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_community_tour_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelernotification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking Update'), ('invite', 'Group Invite'), ('group_invite', 'Tour Group Invite'), ('review', 'Review Reminder'), ('update', 'General Update'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.CreateModel(
            name='OpenTourGroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.opentourgroup')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to='api.userprofile')),
                ('invited_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invites', to='api.userprofile')),
            ],
            options={
                'db_table': 'open_tour_group_invites',
                'unique_together': {('group', 'invited_profile')},
            },
        ),
    ]
