# Generated by Django 5.2.14 on 2026-06-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_invites'),
    ]

    operations = [
    ]
