# Generated by Django 5.2.14 on 2026-06-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_weekly_views_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
