# Generated by Django 5.2.14 on 2026-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemconfig_serviceprovider_availability_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='support_screenshots/'),
        ),
    ]
