# Generated by Django 5.2.14 on 2026-06-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_profile_photo_content_type_and_more'),
        ('api', '0010_create_tour_room_tables'),
    ]

    operations = [
    ]
