# Generated by Django 5.2.14 on 2026-06-16 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_supportticket_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='message_privacy',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('followers', 'Followers Only'), ('no_one', 'No One')], default='anyone', max_length=20),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='read_receipts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Request'), ('active', 'Active'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('is_muted_a', models.BooleanField(default=False)),
                ('is_muted_b', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_conversations', to='api.userprofile')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_a', to='api.userprofile')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_b', to='api.userprofile')),
            ],
            options={
                'db_table': 'conversations',
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, default='')),
                ('shared_media', models.ImageField(blank=True, null=True, upload_to='chat_media/')),
                ('shared_link_type', models.CharField(blank=True, default='', max_length=50)),
                ('shared_link_id', models.CharField(blank=True, default='', max_length=100)),
                ('shared_link_title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.userprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('scam', 'Scam / Fraud'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.conversation')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='api.userprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_conversations', to='api.userprofile')),
            ],
            options={
                'db_table': 'reported_conversations',
            },
        ),
    ]
