# Generated by Django 5.2.14 on 2026-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalaccountsettings',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaccountsettings',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
