# Generated by Django 5.2.14 on 2026-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_trip_stories_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo_content_type',
        ),
        migrations.AlterField(
            model_name='travelernotification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking Update'), ('invite', 'Group Invite'), ('group_invite', 'Tour Group Invite'), ('review', 'Review Reminder'), ('update', 'General Update'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
