# Generated by Django 5.2.14 on 2026-10-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_accountsettings_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourroomchatmessage',
            name='ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tourroomchatmessage',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tourroomchatmessage',
            name='iv',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
