# Generated by Django 5.2.14 on 2026-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_userprofile_profile_photo_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
