# Generated by Django 5.2.14 on 2026-10-01 13:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tourroomchatmessage_ciphertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceprovider',
            name='bank_account_details',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='national_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='bank_account_details',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
