# Generated by Django 5.2.14 on 2026-06-15 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tourroom_cover_photo_tourroom_invite_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boat_type', models.CharField(choices=[('speedboat', 'Speedboat'), ('fishing_boat', 'Fishing Boat'), ('houseboat', 'Houseboat'), ('yacht', 'Yacht'), ('sailboat', 'Sailboat')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('photos', models.BinaryField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_charters', to='api.destination')),
            ],
            options={
                'db_table': 'boat_charters',
                'ordering': ['-rating', '-reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='BoatCharterBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.boatcharter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_charter_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boat_charter_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('guide', 'Tour Guide'), ('driver', 'Driver'), ('translator', 'Translator'), ('photographer', 'Photographer'), ('assistant', 'Travel Assistant')], max_length=20)),
                ('specialties', models.TextField(help_text='Comma-separated specialties')),
                ('languages', models.CharField(help_text='Comma-separated languages', max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.BinaryField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(related_name='guides', to='api.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tour_guides',
                'ordering': ['-rating', '-reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings', to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.tourguide')),
            ],
            options={
                'db_table': 'guide_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('photos', models.BinaryField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rentals', to='api.destination')),
            ],
            options={
                'db_table': 'vehicle_rentals',
                'ordering': ['-rating', '-reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('requirements', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.vehiclerental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rental_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_rental_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoatCharterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField()),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.boatcharter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_charter_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boat_charter_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('charter', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField()),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_reviews', to=settings.AUTH_USER_MODEL)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.tourguide')),
            ],
            options={
                'db_table': 'guide_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('guide', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GuideAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.tourguide')),
            ],
            options={
                'db_table': 'guide_availabilities',
                'ordering': ['date'],
                'unique_together': {('guide', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VehicleRentalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review_text', models.TextField()),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.vehiclerental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rental_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_rental_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('rental', 'user')},
            },
        ),
    ]
