# Generated by Antigravity on 2026-10-01
# Data migration to encrypt existing plain text records for PII fields

from django.db import migrations


def encrypt_existing_pii(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    ServiceProvider = apps.get_model('api', 'ServiceProvider')

    # Re-save each UserProfile through model to encrypt plain-text phone_number & national_id
    for profile in UserProfile.objects.all():
        updated = False
        update_fields = []
        if profile.phone_number and not str(profile.phone_number).startswith('gAAAAA'):
            update_fields.append('phone_number')
            updated = True
        if profile.national_id and not str(profile.national_id).startswith('gAAAAA'):
            update_fields.append('national_id')
            updated = True
        if updated:
            profile.save(update_fields=update_fields)

    # Re-save each ServiceProvider to encrypt plain-text bank_account_details
    for provider in ServiceProvider.objects.all():
        if provider.bank_account_details and not str(provider.bank_account_details).startswith('gAAAAA'):
            provider.save(update_fields=['bank_account_details'])


def reverse_encrypt_existing_pii(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_historicalserviceprovider_bank_account_details_and_more'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_pii, reverse_encrypt_existing_pii),
    ]
