# Generated by Django 5.2.14 on 2026-06-16 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_boatcharter_boatcharterbooking_tourguide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boatcharterreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guidereview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclerentalreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='boatcharterbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boat_charter_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boatcharterreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boat_charter_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guidebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclerentalbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rental_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclerentalreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_rental_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
