from django.urls import path
from .views import (
    DestinationListAPIView,
    DestinationDetailAPIView,
    destination_suggestions,
    GuideListAPIView,
    RouteListAPIView,
    discover_filters,
    register_traveler,
    verify_otp,
    register_service_provider,
    login_view,
    logout_view,
    traveler_dashboard,
    traveler_profile_detail,
    traveler_profile_update,
    traveler_preferences_update,
    traveler_account_settings_update,
    traveler_change_password,
    traveler_profile_photo_update,
    tour_room_list,
    tour_room_detail,
    tour_room_join,
    tour_room_leave,
    tour_room_invite,
    tour_room_members,
    itinerary_items,
    itinerary_item_detail,
    expenses,
    expense_detail,
    expense_participant_payment,
    polls,
    poll_vote,
    poll_close,
    checklist_items,
    checklist_item_detail,
    chat_messages,
    chat_message_pin,
    map_pins,
    map_pin_detail,
    booking_notes,
    booking_note_detail,
    tour_guides,
    tour_guide_detail,
    guide_availabilities,
    guide_reviews,
    guide_bookings,
    guide_booking_detail,
    boat_charters,
    boat_charter_detail,
    boat_charter_reviews,
    boat_charter_bookings,
    boat_charter_booking_detail,
    vehicle_rentals,
    vehicle_rental_detail,
    vehicle_rental_reviews,
    vehicle_rental_bookings,
    vehicle_rental_booking_detail,
)
from .community_views import (
    open_groups_list_create,
    open_group_detail,
    open_group_join,
    open_group_invite,
    my_groups,
    community_feed,
    post_like_toggle,
    post_comments,
    follow_traveler,
)

urlpatterns = [
    path('destinations/suggestions/', destination_suggestions, name='destination-suggestions'),
    path('destinations/', DestinationListAPIView.as_view(), name='destination-list'),
    path('destinations/<slug:slug>/', DestinationDetailAPIView.as_view(), name='destination-detail'),
    path('guides/', GuideListAPIView.as_view(), name='guide-list'),
    path('routes/', RouteListAPIView.as_view(), name='route-list'),
    path('filters/', discover_filters, name='discover-filters'),
    path('auth/register/traveler/', register_traveler, name='register-traveler'),
    path('auth/verify-otp/', verify_otp, name='verify-otp'),
    path('auth/register/service-provider/', register_service_provider, name='register-service-provider'),
    path('auth/login/', login_view, name='login'),
    path('auth/logout/', logout_view, name='logout'),
    path('traveler/dashboard/<int:user_id>/', traveler_dashboard, name='traveler-dashboard'),
    path('traveler/profile/<int:user_id>/', traveler_profile_detail, name='traveler-profile-detail'),
    path('traveler/profile/<int:user_id>/update/', traveler_profile_update, name='traveler-profile-update'),
    path('traveler/profile/<int:user_id>/preferences/', traveler_preferences_update, name='traveler-preferences-update'),
    path('traveler/profile/<int:user_id>/account-settings/', traveler_account_settings_update, name='traveler-account-settings-update'),
    path('traveler/profile/<int:user_id>/change-password/', traveler_change_password, name='traveler-change-password'),
    path('traveler/profile/<int:user_id>/photo/', traveler_profile_photo_update, name='traveler-profile-photo-update'),
    path('community/groups/', open_groups_list_create, name='community-groups'),
    path('community/groups/my/', my_groups, name='community-my-groups'),
    path('community/groups/<int:group_id>/', open_group_detail, name='community-group-detail'),
    path('community/groups/<int:group_id>/join/', open_group_join, name='community-group-join'),
    path('community/groups/<int:group_id>/invite/', open_group_invite, name='community-group-invite'),
    path('community/feed/', community_feed, name='community-feed'),
    path('community/posts/<int:post_id>/like/', post_like_toggle, name='community-post-like'),
    path('community/posts/<int:post_id>/comments/', post_comments, name='community-post-comments'),
    path('community/follow/', follow_traveler, name='community-follow'),
    # Tour Room endpoints
    path('tour-rooms/', tour_room_list, name='tour-room-list'),
    path('tour-rooms/<int:room_id>/', tour_room_detail, name='tour-room-detail'),
    path('tour-rooms/<int:room_id>/join/', tour_room_join, name='tour-room-join'),
    path('tour-rooms/<int:room_id>/leave/', tour_room_leave, name='tour-room-leave'),
    path('tour-rooms/<int:room_id>/invite/', tour_room_invite, name='tour-room-invite'),
    path('tour-rooms/<int:room_id>/members/', tour_room_members, name='tour-room-members'),
    path('tour-rooms/<int:room_id>/itinerary/', itinerary_items, name='tour-room-itinerary'),
    path('tour-rooms/<int:room_id>/itinerary/<int:item_id>/', itinerary_item_detail, name='tour-room-itinerary-detail'),
    path('tour-rooms/<int:room_id>/expenses/', expenses, name='tour-room-expenses'),
    path('tour-rooms/<int:room_id>/expenses/<int:expense_id>/', expense_detail, name='tour-room-expense-detail'),
    path('tour-rooms/<int:room_id>/expenses/<int:expense_id>/participants/<int:participant_id>/', expense_participant_payment, name='tour-room-expense-participant-payment'),
    path('tour-rooms/<int:room_id>/polls/', polls, name='tour-room-polls'),
    path('tour-rooms/<int:room_id>/polls/<int:poll_id>/vote/', poll_vote, name='tour-room-poll-vote'),
    path('tour-rooms/<int:room_id>/polls/<int:poll_id>/close/', poll_close, name='tour-room-poll-close'),
    path('tour-rooms/<int:room_id>/checklist/', checklist_items, name='tour-room-checklist'),
    path('tour-rooms/<int:room_id>/checklist/<int:item_id>/', checklist_item_detail, name='tour-room-checklist-detail'),
    path('tour-rooms/<int:room_id>/chat/', chat_messages, name='tour-room-chat'),
    path('tour-rooms/<int:room_id>/chat/<int:message_id>/pin/', chat_message_pin, name='tour-room-chat-pin'),
    path('tour-rooms/<int:room_id>/map/', map_pins, name='tour-room-map'),
    path('tour-rooms/<int:room_id>/map/<int:pin_id>/', map_pin_detail, name='tour-room-map-detail'),
    path('tour-rooms/<int:room_id>/booking-notes/', booking_notes, name='tour-room-booking-notes'),
    path('tour-rooms/<int:room_id>/booking-notes/<int:note_id>/', booking_note_detail, name='tour-room-booking-note-detail'),
    # Tour Guide & Local Bookings endpoints
    path('tour-guides/', tour_guides, name='tour-guides'),
    path('tour-guides/<int:guide_id>/', tour_guide_detail, name='tour-guide-detail'),
    path('tour-guides/<int:guide_id>/availabilities/', guide_availabilities, name='guide-availabilities'),
    path('tour-guides/<int:guide_id>/reviews/', guide_reviews, name='guide-reviews'),
    path('tour-guides/bookings/', guide_bookings, name='guide-bookings'),
    path('tour-guides/bookings/<int:booking_id>/', guide_booking_detail, name='guide-booking-detail'),
    path('boat-charters/', boat_charters, name='boat-charters'),
    path('boat-charters/<int:charter_id>/', boat_charter_detail, name='boat-charter-detail'),
    path('boat-charters/<int:charter_id>/reviews/', boat_charter_reviews, name='boat-charter-reviews'),
    path('boat-charters/bookings/', boat_charter_bookings, name='boat-charter-bookings'),
    path('boat-charters/bookings/<int:booking_id>/', boat_charter_booking_detail, name='boat-charter-booking-detail'),
    path('vehicle-rentals/', vehicle_rentals, name='vehicle-rentals'),
    path('vehicle-rentals/<int:rental_id>/', vehicle_rental_detail, name='vehicle-rental-detail'),
    path('vehicle-rentals/<int:rental_id>/reviews/', vehicle_rental_reviews, name='vehicle-rental-reviews'),
    path('vehicle-rentals/bookings/', vehicle_rental_bookings, name='vehicle-rental-bookings'),
    path('vehicle-rentals/bookings/<int:booking_id>/', vehicle_rental_booking_detail, name='vehicle-rental-booking-detail'),
]
