from django.urls import path
from .views import (
    DestinationListAPIView,
    DestinationDetailAPIView,
    GuideListAPIView,
    RouteListAPIView,
    discover_filters,
    register_traveler,
    verify_otp,
    register_service_provider,
    login_view,
    logout_view,
    traveler_dashboard,
    traveler_profile_detail,
    traveler_profile_update,
    traveler_preferences_update,
    traveler_account_settings_update,
    traveler_change_password,
    traveler_profile_photo_update,
)
from .community_views import (
    open_groups_list_create,
    open_group_detail,
    open_group_join,
    my_groups,
    community_feed,
    post_like_toggle,
    post_comments,
    follow_traveler,
)

urlpatterns = [
    path('destinations/', DestinationListAPIView.as_view(), name='destination-list'),
    path('destinations/<slug:slug>/', DestinationDetailAPIView.as_view(), name='destination-detail'),
    path('guides/', GuideListAPIView.as_view(), name='guide-list'),
    path('routes/', RouteListAPIView.as_view(), name='route-list'),
    path('filters/', discover_filters, name='discover-filters'),
    path('auth/register/traveler/', register_traveler, name='register-traveler'),
    path('auth/verify-otp/', verify_otp, name='verify-otp'),
    path('auth/register/service-provider/', register_service_provider, name='register-service-provider'),
    path('auth/login/', login_view, name='login'),
    path('auth/logout/', logout_view, name='logout'),
    path('traveler/dashboard/<int:user_id>/', traveler_dashboard, name='traveler-dashboard'),
    path('traveler/profile/<int:user_id>/', traveler_profile_detail, name='traveler-profile-detail'),
    path('traveler/profile/<int:user_id>/update/', traveler_profile_update, name='traveler-profile-update'),
    path('traveler/profile/<int:user_id>/preferences/', traveler_preferences_update, name='traveler-preferences-update'),
    path('traveler/profile/<int:user_id>/account-settings/', traveler_account_settings_update, name='traveler-account-settings-update'),
    path('traveler/profile/<int:user_id>/change-password/', traveler_change_password, name='traveler-change-password'),
    path('traveler/profile/<int:user_id>/photo/', traveler_profile_photo_update, name='traveler-profile-photo-update'),
    path('community/groups/', open_groups_list_create, name='community-groups'),
    path('community/groups/my/', my_groups, name='community-my-groups'),
    path('community/groups/<int:group_id>/', open_group_detail, name='community-group-detail'),
    path('community/groups/<int:group_id>/join/', open_group_join, name='community-group-join'),
    path('community/feed/', community_feed, name='community-feed'),
    path('community/posts/<int:post_id>/like/', post_like_toggle, name='community-post-like'),
    path('community/posts/<int:post_id>/comments/', post_comments, name='community-post-comments'),
    path('community/follow/', follow_traveler, name='community-follow'),
]
